#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lightdm-gtk-greeter
Version  : 2.0.1
Release  : 1
URL      : https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.1/+download/lightdm-gtk-greeter-2.0.1.tar.gz
Source0  : https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.1/+download/lightdm-gtk-greeter-2.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: lightdm-gtk-greeter-bin
Requires: lightdm-gtk-greeter-doc
Requires: lightdm-gtk-greeter-data
Requires: lightdm-gtk-greeter-locales
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(liblightdm-gobject-1)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)

%description
https://launchpad.net/lightdm-gtk-greeter

%package bin
Summary: bin components for the lightdm-gtk-greeter package.
Group: Binaries
Requires: lightdm-gtk-greeter-data

%description bin
bin components for the lightdm-gtk-greeter package.


%package data
Summary: data components for the lightdm-gtk-greeter package.
Group: Data

%description data
data components for the lightdm-gtk-greeter package.


%package doc
Summary: doc components for the lightdm-gtk-greeter package.
Group: Documentation

%description doc
doc components for the lightdm-gtk-greeter package.


%package locales
Summary: locales components for the lightdm-gtk-greeter package.
Group: Default

%description locales
locales components for the lightdm-gtk-greeter package.


%prep
%setup -q -n lightdm-gtk-greeter-2.0.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang lightdm-gtk-greeter

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lightdm-gtk-greeter

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/scalable/places/gnome-classic_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-fallback-compiz_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-fallback_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-flashback-compiz_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-flashback_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-shell_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/kde-plasma_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/kde_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/lubuntu_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/lxde_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/mate_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/pantheon_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntu-2d_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntu_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntustudio_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/wmaker-common_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xfce_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xterm_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xubuntu_badge-symbolic.svg
/usr/share/xgreeters/lightdm-gtk-greeter.desktop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/lightdm-gtk-greeter/*

%files locales -f lightdm-gtk-greeter.lang 
%defattr(-,root,root,-)

