#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x76E6FEEC95FC5E22 (smd.seandavis@gmail.com)
#
Name     : lightdm-gtk-greeter
Version  : 2.0.6
Release  : 7
URL      : https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.6/+download/lightdm-gtk-greeter-2.0.6.tar.gz
Source0  : https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.6/+download/lightdm-gtk-greeter-2.0.6.tar.gz
Source1  : https://launchpad.net/lightdm-gtk-greeter/2.0/2.0.6/+download/lightdm-gtk-greeter-2.0.6.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: lightdm-gtk-greeter-bin = %{version}-%{release}
Requires: lightdm-gtk-greeter-data = %{version}-%{release}
Requires: lightdm-gtk-greeter-license = %{version}-%{release}
Requires: lightdm-gtk-greeter-locales = %{version}-%{release}
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(liblightdm-gobject-1)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)

%description
https://launchpad.net/lightdm-gtk-greeter

%package bin
Summary: bin components for the lightdm-gtk-greeter package.
Group: Binaries
Requires: lightdm-gtk-greeter-data = %{version}-%{release}
Requires: lightdm-gtk-greeter-license = %{version}-%{release}

%description bin
bin components for the lightdm-gtk-greeter package.


%package data
Summary: data components for the lightdm-gtk-greeter package.
Group: Data

%description data
data components for the lightdm-gtk-greeter package.


%package doc
Summary: doc components for the lightdm-gtk-greeter package.
Group: Documentation

%description doc
doc components for the lightdm-gtk-greeter package.


%package license
Summary: license components for the lightdm-gtk-greeter package.
Group: Default

%description license
license components for the lightdm-gtk-greeter package.


%package locales
Summary: locales components for the lightdm-gtk-greeter package.
Group: Default

%description locales
locales components for the lightdm-gtk-greeter package.


%prep
%setup -q -n lightdm-gtk-greeter-2.0.6
cd %{_builddir}/lightdm-gtk-greeter-2.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604609842
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604609842
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lightdm-gtk-greeter
cp %{_builddir}/lightdm-gtk-greeter-2.0.6/COPYING %{buildroot}/usr/share/package-licenses/lightdm-gtk-greeter/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang lightdm-gtk-greeter

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lightdm-gtk-greeter

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/scalable/places/budgie-desktop_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-classic_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-fallback-compiz_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-fallback_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-flashback-compiz_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-flashback_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome-shell_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/gnome_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/kde-plasma_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/kde_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/lubuntu_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/lxde_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/mate_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/pantheon_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntu-2d_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntu_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/ubuntustudio_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/wmaker-common_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xfce_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xterm_badge-symbolic.svg
/usr/share/icons/hicolor/scalable/places/xubuntu_badge-symbolic.svg
/usr/share/xgreeters/lightdm-gtk-greeter.desktop

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/lightdm\-gtk\-greeter/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lightdm-gtk-greeter/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files locales -f lightdm-gtk-greeter.lang
%defattr(-,root,root,-)

